In [141]:
import numpy as np

In [142]:
np.random.seed(42)
K, N = 4, 5
A1 = np.random.rand(K,N)
A2 = np.random.rand(K,N)

In [143]:
A1,A2

(array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
        [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
        [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
        [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914]]),
 array([[0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998],
        [0.78517596, 0.19967378, 0.51423444, 0.59241457, 0.04645041],
        [0.60754485, 0.17052412, 0.06505159, 0.94888554, 0.96563203],
        [0.80839735, 0.30461377, 0.09767211, 0.68423303, 0.44015249]]))

## Matrix Correlation Coefficient

In [144]:
def ACC(A1,A2):
    corr = np.zeros((K,K))
    for i in range(K):
        for j in range(K):
            corr[i][j] = np.corrcoef(A1[:,i], A2[:,j])[0][1]
    
    max_list = []
    for _ in range(K):
        row, column = np.unravel_index(corr.argmax(), corr.shape)
        max_list.append(corr[row][column])
        corr = np.delete(corr, row, axis=0)
        corr = np.delete(corr, column, axis=1)
    
    return np.mean(max_list)

In [145]:
ACC(A1,A2)

0.05919772889855576

## Normalised Mutual Information

In [146]:
def calcMI(A1,A2):
    P = A1@A2.T
    PXY=P/sum(sum(P))
    PXPY=np.outer(np.sum(PXY,axis=1), np.sum(PXY,axis=0))
    ind = np.where(PXY>0)
    MI=sum(PXY[ind]*np.log(PXY[ind]/PXPY[ind]))
    return MI

In [147]:
def calcNMI(A1,A2): 
    NMI = (2*calcMI(A1,A2)) / (calcMI(A1,A1) + calcMI(A2,A2))
    return NMI

In [148]:
calcNMI(S,A)

0.16568712557600532

## Response Bias Analysis

In [149]:
b1 = np.arange(5)[1:]/5
b2 = np.array([0.3,0.4,0.7,0.8])
b1,b2

(array([0.2, 0.4, 0.6, 0.8]), array([0.3, 0.4, 0.7, 0.8]))

In [150]:
def rba(b1,b2):
    total = 0
    k = b1.shape[0]
    for i in range(k):
        total += abs(b1[i]-b2[i])
    return total/k

In [151]:
rba(b1,b2)

0.04999999999999999

Notér at boundaries ikke må indeholde de første og sidste værdier (altså 0 og 1)